# Generated by Django 2.2.5 on 2022-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=1000)),
            ],
        ),
    ]
